# Generated by Django 3.2.8 on 2021-11-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': ''},
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
