# Generated by Django 3.2.8 on 2021-11-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_school', '0002_auto_20211101_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
